spring:
  cloud:
    gateway:
      routes:
        - id: Microservice1
          uri: http://localhost:8081/
          Predicates:
            - Path=/accountsB/**
        - id: MicroService2
          uri: http://localhost:8082/
          Predicates:
            - Path=/accountsA/**
    compatibility-verifier:
      enabled: false
server:
  port: 8088
  error.include-message: always